### ISSUE TITLE
Cannot seem to run from dev

### ISSUE THREAD

**Issue by ghost** [nguyennv/openpgp-zimlet#10]
Most zimlets support running in dev mode, to make debugging easy, but for some reason this zimlet does not seem to support that.

How can I install openpgp-secure-zimlet in dev mode?

https://myzimbra.com/?dev=1
/opt/zimbra/zimlets-deployed/_dev/openpgp_zimbra_secure

https://wiki.zimbra.com/wiki/Zimlet_Developers_Guide:Dev_Environment_Setup

Supporting this will eventually make it easier to support this code on future releases. As there are lots of overrides in this Zimlet.

**Comment by nguyennv** [comment]
Developer now can install openpgp-secure-zimlet in dev mode by running install-dev.sh
