### ISSUE TITLE
Stay up to date with DOMPurify

### ISSUE THREAD

**Issue by plobbes** [nguyennv/openpgp-zimlet#19]
It would be great to stay up to date with the latest DOMPurify, instead of pulling in (and distributing) an older version.  There's certainly more than one way to go about it, and I'm not sure what you'd prefer to do, but it would be worthwhile to pick a method and document that instead of the current status quo.

**Comment by ghost** [comment]
I have been including dom purify in a number of zimlets as well, my vote
is, include it in the zimbra ajax client.

So we can all just use it, and stop redistribute it all the time.

**Comment by nguyennv** [comment]
Update DOMPurify to version 0.9.0
