### ISSUE TITLE
does not display utf-8 correctly on decrypted message

### ISSUE THREAD

**Issue by ghost** [nguyennv/openpgp-zimlet#2]
See attached
![2016-12-07-113100_3840x1080_scrot](https://cloud.githubusercontent.com/assets/4353213/20964166/b49ffbf4-bc70-11e6-8430-87fb828c777d.png)

https://github.com/Zimbra-Community/pgp-zimlet/blob/stable/test/all-testcases.tgz

https://github.com/Zimbra-Community/pgp-zimlet/blob/stable/test/thunderbird-engimail-test-keypair.txt

**Comment by nguyennv** [comment]
Hi Barry de Graaff,
Thanks for your reporting.
I added utf-8 content decoding on decrypted message.
