### ISSUE TITLE
option to store keys on the server

### ISSUE THREAD

**Issue by ghost** [nguyennv/openpgp-zimlet#7]
Could you add an option to store keys on the server (at least the public keys) OR support reading them from contacts.

We could add a special field to the contacts to achieve this.

**Comment by jorgedlcruz** [comment]
+1

**Comment by nguyennv** [comment]
I'll implement this option by adding 2 buttons: "Save to Contacts" for saving public keys to user contact list and "Load from Contacs" for reading public key from user contacts.
Any suggestion about this implementation?

**Comment by ghost** [comment]
Best would be to have an option that a user can enable: `enable contacts scanning`

Once cheched, do a rest api call to this:
  url[i++] = "/home/";
   url[i++]= AjxStringUtil.urlComponentEncode(appCtxt.getActiveAccount().name);
   url[i++] = "/Contacts?fmt=txt&charset=UTF-8";

Also you would need to check for changes to contacts, you could do that by checking for onContactEdit and onShowView

https://github.com/Zimbra-Community/pgp-zimlet/blob/stable/tk_barrydegraaff_zimbra_openpgp/tk_barrydegraaff_zimbra_openpgp.js#L342

Thanks for considering!

**Comment by ghost** [comment]
In any way, an implementation that would NOT require the user to re-do something when they log onto a different computer would be key.

**Comment by ghost** [comment]
Also this would allow users to migrate from and to Zimbra OpenPGP Zimlet more seamlessly. Suggest maybe you implement this as well:
https://github.com/Zimbra-Community/io_nomennesc_extracontact

An additional field in the contacts to store the pubkey.

**Comment by nguyennv** [comment]
Zimlet now auto scan public keys from user's  contacts.

**Comment by ghost** [comment]
Can you put a note on it in the readme, also does it use the notes field or a separate custom field?

**Comment by ghost** [comment]
Thanks!
